# Generated by Django 5.1.1 on 2024-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='transportation_mode',
            field=models.CharField(choices=[('truck', 'Truck'), ('air', 'Air'), ('ship', 'Ship'), ('train', 'Train'), ('other', 'Other')], default='truck', max_length=20),
        ),
    ]
